services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:

    image: postgres:latest

    ports:
      - "5432:5432"

    env_file:
      - .env

    environment:
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_USER: ${db_username}
      POSTGRES_DB: postgres

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"