spring.application.name=blog

#Security
jwt.secret=${key}
jwt.expiry=1000000
refresh.expiry=864000000
admin.email=${admin_email}
admin.password=${admin_password}

stripe.secret.test=${stripe_secret_test}
stripe.webhook.secret=${stripe.webhook.secret}

server.port=8080

# Database (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update


# Redis
spring.data.redis.port=6379
spring.data.redis.host=localhost