spring.application.name=blog

jwt.secret=${key}
jwt.expiry=1000000
refresh.expiry=864000000
admin.email=${admin_email}
admin.password=${admin_password}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=${db_password}
spring.datasource.username=${db_username}

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.host=localhost
spring.data.redis.port=6379
